### load an Excel dataset to this Python programming environment

In [2]:
# import libraries

import pandas as pd
import numpy as np
import os

In [3]:
curr_dir = os.getcwd()

In [4]:
# current working directory is the location of this jupyter notebook on my hard drive. 
print(curr_dir)

C:\Users\ZXT3080\GitHub\PythonIntroAndDataModeling\notebooks\BAN7101BusinessAnalytics

In [8]:
### specify a dataset file path that is relevent to our current working directory. 
file_path = 'College Basketball Dataset-2019.csv'

### read the dataset using Python command
df = pd.read_csv(file_path)


### full path setting
f_path = 'C:/Users/ZXT3080/GitHub/PythonIntroAndDataModeling/notebooks/BAN7101BusinessAnalytics/College Basketball Dataset-2019.csv'

ddf = pd.read_csv(f_path)

# show dataframes
df, ddf

(                       TEAM  CONF   G   W  ADJOE  ADJDE  BARTHAG  EFG_O  \
 0                   Gonzaga   WCC  37  33  123.4   89.9   0.9744   59.0
 1                  Virginia   ACC  38  35  123.0   89.9   0.9736   55.2
 2                      Duke   ACC  38  32  118.9   89.2   0.9646   53.6
 3            North Carolina   ACC  36  29  120.1   91.4   0.9582   52.9
 4                  Michigan   B10  37  30  114.6   85.6   0.9665   51.6
 ..                      ...   ...  ..  ..    ...    ...      ...    ...
 348              Alcorn St.  SWAC  27  10   89.0  112.6   0.0628   45.7
 349           New Hampshire    AE  27   5   83.7  106.1   0.0613   44.0
 350             Chicago St.   WAC  30   3   88.5  117.3   0.0380   44.2
 351            Delaware St.  MEAC  29   6   84.3  112.2   0.0358   40.0
 352  Maryland Eastern Shore  MEAC  30   7   85.7  114.4   0.0346   43.5

      EFG_D   TOR  ...   FTR  FTRD  2P_O  2P_D  3P_O  3P_D  ADJ_T   WAB  \
 0     44.2  14.9  ...  35.3  25.9  61.4  43.4  36.3  30.4   72.0   7.0
 1     44.7  14.7  ...  29.1  26.3  52.5  45.7  39.5  28.9   60.7  11.1
 2     45.0  17.5  ...  33.2  24.0  58.0  45.0  30.8  29.9   73.6  11.2
 3     48.9  17.2  ...  30.2  28.4  52.1  47.9  36.2  33.5   76.0  10.0
 4     44.1  13.9  ...  27.5  24.1  51.8  44.3  34.2  29.1   65.9   9.2
 ..     ...   ...  ...   ...   ...   ...   ...   ...   ...    ...   ...
 348   52.7  24.1  ...  30.5  36.5  45.0  55.3  31.3  32.1   67.1 -16.7
 349   51.5  18.4  ...  21.9  38.0  39.4  52.1  32.6  33.6   67.1 -20.2
 350   57.8  22.5  ...  33.1  33.9  43.5  57.9  30.7  38.5   71.9 -20.9
 351   52.4  19.0  ...  25.5  39.2  37.7  52.6  29.0  34.7   71.6 -21.7
 352   54.4  20.7  ...  28.3  36.6  44.5  53.2  27.9  37.3   64.5 -19.9

      POSTSEASON  SEED
 0            E8   1.0
 1     Champions   1.0
 2            E8   1.0
 3           S16   1.0
 4           S16   2.0
 ..          ...   ...
 348         NaN   NaN
 349         NaN   NaN
 350         NaN   NaN
 351         NaN   NaN
 352         NaN   NaN

 [353 rows x 23 columns],
                        TEAM  CONF   G   W  ADJOE  ADJDE  BARTHAG  EFG_O  \
 0                   Gonzaga   WCC  37  33  123.4   89.9   0.9744   59.0
 1                  Virginia   ACC  38  35  123.0   89.9   0.9736   55.2
 2                      Duke   ACC  38  32  118.9   89.2   0.9646   53.6
 3            North Carolina   ACC  36  29  120.1   91.4   0.9582   52.9
 4                  Michigan   B10  37  30  114.6   85.6   0.9665   51.6
 ..                      ...   ...  ..  ..    ...    ...      ...    ...
 348              Alcorn St.  SWAC  27  10   89.0  112.6   0.0628   45.7
 349           New Hampshire    AE  27   5   83.7  106.1   0.0613   44.0
 350             Chicago St.   WAC  30   3   88.5  117.3   0.0380   44.2
 351            Delaware St.  MEAC  29   6   84.3  112.2   0.0358   40.0
 352  Maryland Eastern Shore  MEAC  30   7   85.7  114.4   0.0346   43.5

      EFG_D   TOR  ...   FTR  FTRD  2P_O  2P_D  3P_O  3P_D  ADJ_T   WAB  \
 0     44.2  14.9  ...  35.3  25.9  61.4  43.4  36.3  30.4   72.0   7.0
 1     44.7  14.7  ...  29.1  26.3  52.5  45.7  39.5  28.9   60.7  11.1
 2     45.0  17.5  ...  33.2  24.0  58.0  45.0  30.8  29.9   73.6  11.2
 3     48.9  17.2  ...  30.2  28.4  52.1  47.9  36.2  33.5   76.0  10.0
 4     44.1  13.9  ...  27.5  24.1  51.8  44.3  34.2  29.1   65.9   9.2
 ..     ...   ...  ...   ...   ...   ...   ...   ...   ...    ...   ...
 348   52.7  24.1  ...  30.5  36.5  45.0  55.3  31.3  32.1   67.1 -16.7
 349   51.5  18.4  ...  21.9  38.0  39.4  52.1  32.6  33.6   67.1 -20.2
 350   57.8  22.5  ...  33.1  33.9  43.5  57.9  30.7  38.5   71.9 -20.9
 351   52.4  19.0  ...  25.5  39.2  37.7  52.6  29.0  34.7   71.6 -21.7
 352   54.4  20.7  ...  28.3  36.6  44.5  53.2  27.9  37.3   64.5 -19.9

      POSTSEASON  SEED
 0            E8   1.0
 1     Champions   1.0
 2            E8   1.0
 3           S16   1.0
 4           S16   2.0
 ..          ...   ...
 348         NaN   NaN
 349         NaN   NaN
 350         NaN   NaN
 351         NaN   NaN
 352         NaN   NaN

 [353 rows x 23 columns])

In [6]:
### To find the relationship between the location folder of the data file and the current working directory, 
### you can start with the current working directory.

filePath = '../../data/College Basketball Dataset.csv'

dataframe = pd.read_csv(filePath)

dataframe

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
4,Kentucky,SEC,40,29,117.2,96.2,0.9062,49.9,46.0,18.1,...,36.8,50.0,44.9,33.2,32.2,65.9,3.9,2ND,8.0,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097,Michigan St.,B10,35,26,111.4,87.8,0.9392,50.6,44.5,20.8,...,32.4,50.4,44.3,34.1,30.1,64.4,6.7,S16,3.0,2013
2098,Arizona,P12,35,27,114.4,92.2,0.9229,52.5,46.6,19.5,...,32.9,50.6,43.4,37.1,35.8,66.8,4.6,S16,6.0,2013
2099,Oregon,P12,37,28,104.8,88.6,0.8728,49.3,46.4,21.4,...,33.3,49.1,44.9,33.3,33.4,69.2,2.9,S16,12.0,2013
2100,La Salle,A10,34,24,112.0,96.2,0.8516,51.9,49.3,17.1,...,28.5,49.3,50.6,37.7,30.2,66.0,0.3,S16,13.0,2013
2101,Florida Gulf Coast,ASun,35,24,103.4,96.3,0.6952,51.6,46.9,21.0,...,32.7,52.3,46.9,33.4,31.3,69.1,-4.0,S16,15.0,2013

In [7]:
### if you want to specify the file path without knowing the relationship
### between current working directlry and dataset file location

filepath = 'C:/Users/ZXT3080/GitHub/PythonIntroAndDataModeling/data/College Basketball Dataset.csv'

dframe = pd.read_csv(filepath)

dframe

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
4,Kentucky,SEC,40,29,117.2,96.2,0.9062,49.9,46.0,18.1,...,36.8,50.0,44.9,33.2,32.2,65.9,3.9,2ND,8.0,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097,Michigan St.,B10,35,26,111.4,87.8,0.9392,50.6,44.5,20.8,...,32.4,50.4,44.3,34.1,30.1,64.4,6.7,S16,3.0,2013
2098,Arizona,P12,35,27,114.4,92.2,0.9229,52.5,46.6,19.5,...,32.9,50.6,43.4,37.1,35.8,66.8,4.6,S16,6.0,2013
2099,Oregon,P12,37,28,104.8,88.6,0.8728,49.3,46.4,21.4,...,33.3,49.1,44.9,33.3,33.4,69.2,2.9,S16,12.0,2013
2100,La Salle,A10,34,24,112.0,96.2,0.8516,51.9,49.3,17.1,...,28.5,49.3,50.6,37.7,30.2,66.0,0.3,S16,13.0,2013
2101,Florida Gulf Coast,ASun,35,24,103.4,96.3,0.6952,51.6,46.9,21.0,...,32.7,52.3,46.9,33.4,31.3,69.1,-4.0,S16,15.0,2013

In [9]:
dframe.describe()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,YEAR
count,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,...,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,2102.000000,408.000000,2102.000000
mean,31.450048,16.145100,103.299191,103.299286,0.494082,49.671503,49.871551,18.789343,18.717460,30.149334,...,36.499524,36.785109,48.591056,48.765509,34.426308,34.629448,67.584539,-7.805661,8.803922,2015.504757
std,2.678937,6.641093,7.436838,6.632112,0.256843,3.157149,2.950618,2.093918,2.218793,4.104225,...,5.161784,6.276590,3.342773,3.330265,2.829677,2.428083,3.312176,6.941119,4.678434,1.706366
min,15.000000,0.000000,76.600000,84.000000,0.005000,39.200000,39.600000,11.900000,10.200000,15.000000,...,21.600000,22.100000,38.300000,37.700000,24.900000,27.100000,57.200000,-25.200000,1.000000,2013.000000
25%,30.000000,11.000000,98.225000,98.500000,0.282650,47.600000,47.800000,17.400000,17.200000,27.400000,...,32.900000,32.400000,46.400000,46.500000,32.500000,33.000000,65.400000,-12.975000,5.000000,2014.000000
50%,31.000000,16.000000,102.900000,103.300000,0.474600,49.600000,49.900000,18.700000,18.650000,30.200000,...,36.300000,36.400000,48.500000,48.800000,34.400000,34.600000,67.600000,-8.200000,9.000000,2016.000000
75%,33.000000,21.000000,108.100000,107.900000,0.714275,51.700000,51.900000,20.100000,20.100000,32.900000,...,40.000000,40.875000,50.800000,51.100000,36.300000,36.300000,69.800000,-3.200000,13.000000,2017.000000
max,40.000000,38.000000,129.100000,124.000000,0.984200,59.800000,59.500000,27.100000,28.500000,43.600000,...,58.600000,60.700000,62.600000,59.800000,44.100000,43.100000,83.400000,13.100000,16.000000,2018.000000

In [ ]:
write a statement about your findings.
then go next.